# Generated by Django 3.1.3 on 2021-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=60, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.RenameField(
            model_name='division',
            old_name='name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='division',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион'),
        ),
    ]
