# Generated by Django 3.1.3 on 2021-05-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0002_auto_20210523_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOLO.division'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SOLO.positions'),
        ),
    ]
