# Generated by Django 3.1.3 on 2021-05-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0003_auto_20210523_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_code',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Доп код'),
        ),
    ]
