# Generated by Django 3.1.3 on 2021-05-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0007_positions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='name',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='СМО'),
        ),
    ]
