# Generated by Django 3.1.3 on 2021-05-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0009_auto_20210523_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positions',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должностьи'},
        ),
    ]
