# Generated by Django 3.1.3 on 2021-05-22 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0010_auto_20210523_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SOLO.positions', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='Vocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254, verbose_name='Пользователь')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.BooleanField(default=True, max_length=10, verbose_name='Статус')),
                ('employer', models.IntegerField(blank=True, null=True, verbose_name='Работодатель')),
                ('interested', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Интересуются')),
            ],
            options={
                'verbose_name': 'Вокансия',
                'verbose_name_plural': 'Вокансии',
            },
        ),
    ]
