# Generated by Django 3.1.3 on 2021-05-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0015_auto_20210523_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocation',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='vocation',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
    ]
