# Generated by Django 3.1.3 on 2021-05-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOLO', '0017_auto_20210523_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подразделения'),
        ),
        migrations.AddField(
            model_name='interest',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_leader',
            field=models.BooleanField(default=False, verbose_name='Лидер'),
        ),
    ]
